/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'activityType' : ActivityType,
  'sport' : Sport,
  'notes' : string,
  'timestamp' : Timestamp,
}
export type ActivityType = { 'solo' : null } |
  { 'group' : null };
export type ObjectiveStatus = { 'active' : null } |
  { 'completed' : null };
export type Sport = string;
export interface TeamObjective {
  'id' : bigint,
  'status' : ObjectiveStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'currentProgress' : bigint,
  'description' : string,
  'sport' : Sport,
  'rewardText' : string,
  'rewardBadge' : string,
  'targetCount' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserObjective {
  'progress' : bigint,
  'objectiveId' : bigint,
  'acceptedAt' : Timestamp,
}
export interface UserProfile {
  'id' : UserId,
  'name' : string,
  'onboardingComplete' : boolean,
  'sports' : Array<Sport>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WellnessTip {
  'tip' : string,
  'socialBattery' : bigint,
  'generatedAt' : Timestamp,
  'isBurnoutRisk' : boolean,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptTeamObjective' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAvailableSports' : ActorMethod<[], Array<Sport>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyActivities' : ActorMethod<[], Array<Activity>>,
  'getMyObjectives' : ActorMethod<[], Array<[TeamObjective, UserObjective]>>,
  'getMySocialBattery' : ActorMethod<[], bigint>,
  'getMyWellnessTip' : ActorMethod<[], [] | [WellnessTip]>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOpenAIConfigured' : ActorMethod<[], boolean>,
  'listTeamObjectives' : ActorMethod<[], Array<TeamObjective>>,
  'logActivity' : ActorMethod<[Sport, ActivityType, string], Activity>,
  'refreshMyWellnessTip' : ActorMethod<[], WellnessTip>,
  'saveCallerUserProfile' : ActorMethod<
    [string, Array<Sport>, boolean],
    undefined
  >,
  'setOpenAIApiKey' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];