/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Sport = IDL.Text;
export const UserId = IDL.Principal;
export const UserProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'onboardingComplete' : IDL.Bool,
  'sports' : IDL.Vec(Sport),
});
export const ActivityType = IDL.Variant({
  'solo' : IDL.Null,
  'group' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'activityType' : ActivityType,
  'sport' : Sport,
  'notes' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ObjectiveStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
});
export const TeamObjective = IDL.Record({
  'id' : IDL.Nat,
  'status' : ObjectiveStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'currentProgress' : IDL.Nat,
  'description' : IDL.Text,
  'sport' : Sport,
  'rewardText' : IDL.Text,
  'rewardBadge' : IDL.Text,
  'targetCount' : IDL.Nat,
});
export const UserObjective = IDL.Record({
  'progress' : IDL.Nat,
  'objectiveId' : IDL.Nat,
  'acceptedAt' : Timestamp,
});
export const WellnessTip = IDL.Record({
  'tip' : IDL.Text,
  'socialBattery' : IDL.Nat,
  'generatedAt' : Timestamp,
  'isBurnoutRisk' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptTeamObjective' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAvailableSports' : IDL.Func([], [IDL.Vec(Sport)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getMyObjectives' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TeamObjective, UserObjective))],
      ['query'],
    ),
  'getMySocialBattery' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyWellnessTip' : IDL.Func([], [IDL.Opt(WellnessTip)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listTeamObjectives' : IDL.Func([], [IDL.Vec(TeamObjective)], ['query']),
  'logActivity' : IDL.Func([Sport, ActivityType, IDL.Text], [Activity], []),
  'refreshMyWellnessTip' : IDL.Func([], [WellnessTip], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Vec(Sport), IDL.Bool],
      [],
      [],
    ),
  'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Sport = IDL.Text;
  const UserId = IDL.Principal;
  const UserProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'onboardingComplete' : IDL.Bool,
    'sports' : IDL.Vec(Sport),
  });
  const ActivityType = IDL.Variant({ 'solo' : IDL.Null, 'group' : IDL.Null });
  const Timestamp = IDL.Int;
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'activityType' : ActivityType,
    'sport' : Sport,
    'notes' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ObjectiveStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
  });
  const TeamObjective = IDL.Record({
    'id' : IDL.Nat,
    'status' : ObjectiveStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'currentProgress' : IDL.Nat,
    'description' : IDL.Text,
    'sport' : Sport,
    'rewardText' : IDL.Text,
    'rewardBadge' : IDL.Text,
    'targetCount' : IDL.Nat,
  });
  const UserObjective = IDL.Record({
    'progress' : IDL.Nat,
    'objectiveId' : IDL.Nat,
    'acceptedAt' : Timestamp,
  });
  const WellnessTip = IDL.Record({
    'tip' : IDL.Text,
    'socialBattery' : IDL.Nat,
    'generatedAt' : Timestamp,
    'isBurnoutRisk' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptTeamObjective' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAvailableSports' : IDL.Func([], [IDL.Vec(Sport)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getMyObjectives' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TeamObjective, UserObjective))],
        ['query'],
      ),
    'getMySocialBattery' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyWellnessTip' : IDL.Func([], [IDL.Opt(WellnessTip)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listTeamObjectives' : IDL.Func([], [IDL.Vec(TeamObjective)], ['query']),
    'logActivity' : IDL.Func([Sport, ActivityType, IDL.Text], [Activity], []),
    'refreshMyWellnessTip' : IDL.Func([], [WellnessTip], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Vec(Sport), IDL.Bool],
        [],
        [],
      ),
    'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };