/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface TeamObjective {
    id: bigint;
    status: ObjectiveStatus;
    title: string;
    createdAt: Timestamp;
    currentProgress: bigint;
    description: string;
    sport: Sport;
    rewardText: string;
    rewardBadge: string;
    targetCount: bigint;
}
export type Sport = string;
export interface Activity {
    id: bigint;
    activityType: ActivityType;
    sport: Sport;
    notes: string;
    timestamp: Timestamp;
}
export interface WellnessTip {
    tip: string;
    socialBattery: bigint;
    generatedAt: Timestamp;
    isBurnoutRisk: boolean;
}
export interface UserObjective {
    progress: bigint;
    objectiveId: bigint;
    acceptedAt: Timestamp;
}
export interface UserProfile {
    id: UserId;
    name: string;
    onboardingComplete: boolean;
    sports: Array<Sport>;
}
export enum ActivityType {
    solo = "solo",
    group = "group"
}
export enum ObjectiveStatus {
    active = "active",
    completed = "completed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    acceptTeamObjective(objectiveId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAvailableSports(): Promise<Array<Sport>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyActivities(): Promise<Array<Activity>>;
    getMyObjectives(): Promise<Array<[TeamObjective, UserObjective]>>;
    getMySocialBattery(): Promise<bigint>;
    getMyWellnessTip(): Promise<WellnessTip | null>;
    getUserProfile(user: UserId): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isOpenAIConfigured(): Promise<boolean>;
    listTeamObjectives(): Promise<Array<TeamObjective>>;
    logActivity(sport: Sport, activityType: ActivityType, notes: string): Promise<Activity>;
    refreshMyWellnessTip(): Promise<WellnessTip>;
    saveCallerUserProfile(name: string, sports: Array<Sport>, onboardingComplete: boolean): Promise<void>;
    setOpenAIApiKey(key: string): Promise<void>;
}
import type { Activity as _Activity, ActivityType as _ActivityType, ObjectiveStatus as _ObjectiveStatus, Sport as _Sport, TeamObjective as _TeamObjective, Timestamp as _Timestamp, UserObjective as _UserObjective, UserProfile as _UserProfile, UserRole as _UserRole, WellnessTip as _WellnessTip } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptTeamObjective(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptTeamObjective(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptTeamObjective(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAvailableSports(): Promise<Array<Sport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSports();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyActivities();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyActivities();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyObjectives(): Promise<Array<[TeamObjective, UserObjective]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyObjectives();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyObjectives();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySocialBattery(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySocialBattery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySocialBattery();
            return result;
        }
    }
    async getMyWellnessTip(): Promise<WellnessTip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWellnessTip();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWellnessTip();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: UserId): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOpenAIConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOpenAIConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOpenAIConfigured();
            return result;
        }
    }
    async listTeamObjectives(): Promise<Array<TeamObjective>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeamObjectives();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeamObjectives();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async logActivity(arg0: Sport, arg1: ActivityType, arg2: string): Promise<Activity> {
        if (this.processError) {
            try {
                const result = await this.actor.logActivity(arg0, to_candid_ActivityType_n19(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Activity_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logActivity(arg0, to_candid_ActivityType_n19(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Activity_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async refreshMyWellnessTip(): Promise<WellnessTip> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshMyWellnessTip();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshMyWellnessTip();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: Array<Sport>, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async setOpenAIApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpenAIApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpenAIApiKey(arg0);
            return result;
        }
    }
}
function from_candid_ActivityType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Activity_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ObjectiveStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ObjectiveStatus): ObjectiveStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TeamObjective_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamObjective): TeamObjective {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WellnessTip]): WellnessTip | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ObjectiveStatus;
    title: string;
    createdAt: _Timestamp;
    currentProgress: bigint;
    description: string;
    sport: _Sport;
    rewardText: string;
    rewardBadge: string;
    targetCount: bigint;
}): {
    id: bigint;
    status: ObjectiveStatus;
    title: string;
    createdAt: Timestamp;
    currentProgress: bigint;
    description: string;
    sport: Sport;
    rewardText: string;
    rewardBadge: string;
    targetCount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ObjectiveStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        currentProgress: value.currentProgress,
        description: value.description,
        sport: value.sport,
        rewardText: value.rewardText,
        rewardBadge: value.rewardBadge,
        targetCount: value.targetCount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    activityType: _ActivityType;
    sport: _Sport;
    notes: string;
    timestamp: _Timestamp;
}): {
    id: bigint;
    activityType: ActivityType;
    sport: Sport;
    notes: string;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        activityType: from_candid_ActivityType_n9(_uploadFile, _downloadFile, value.activityType),
        sport: value.sport,
        notes: value.notes,
        timestamp: value.timestamp
    };
}
function from_candid_tuple_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_TeamObjective, _UserObjective]): [TeamObjective, UserObjective] {
    return [
        from_candid_TeamObjective_n13(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    solo: null;
} | {
    group: null;
}): ActivityType {
    return "solo" in value ? ActivityType.solo : "group" in value ? ActivityType.group : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
}): ObjectiveStatus {
    return "active" in value ? ObjectiveStatus.active : "completed" in value ? ObjectiveStatus.completed : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_TeamObjective, _UserObjective]>): Array<[TeamObjective, UserObjective]> {
    return value.map((x)=>from_candid_tuple_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamObjective>): Array<TeamObjective> {
    return value.map((x)=>from_candid_TeamObjective_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n7(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): {
    solo: null;
} | {
    group: null;
} {
    return value == ActivityType.solo ? {
        solo: null
    } : value == ActivityType.group ? {
        group: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
